// <auto-generated />
namespace MobWeb.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AttMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttMap));
        
        string IMigrationMetadata.Id
        {
            get { return "201810172027593_AttMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
